// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJVvTjdC1b3U6lQ2hhrwbgfcAQtVjcre4',
    appId: '1:728312549391:web:b2bb7fe6f26bc41465537a',
    messagingSenderId: '728312549391',
    projectId: 'my-notes-firebase-learning',
    authDomain: 'my-notes-firebase-learning.firebaseapp.com',
    storageBucket: 'my-notes-firebase-learning.appspot.com',
    measurementId: 'G-2RGXBMRY8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT-JjwKE0nqpzDqKR8VYWAYUWWgQwwjf8',
    appId: '1:728312549391:android:d83719460f40641465537a',
    messagingSenderId: '728312549391',
    projectId: 'my-notes-firebase-learning',
    storageBucket: 'my-notes-firebase-learning.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtKjNlp_SbHErI8yFs0HzsVjBvKsY94Bg',
    appId: '1:728312549391:ios:4dd3c67e6c883c8165537a',
    messagingSenderId: '728312549391',
    projectId: 'my-notes-firebase-learning',
    storageBucket: 'my-notes-firebase-learning.appspot.com',
    iosClientId: '728312549391-0otuv3h3q2207r4oljiqjld52hkn05a9.apps.googleusercontent.com',
    iosBundleId: 'com.shark.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtKjNlp_SbHErI8yFs0HzsVjBvKsY94Bg',
    appId: '1:728312549391:ios:4dd3c67e6c883c8165537a',
    messagingSenderId: '728312549391',
    projectId: 'my-notes-firebase-learning',
    storageBucket: 'my-notes-firebase-learning.appspot.com',
    iosClientId: '728312549391-0otuv3h3q2207r4oljiqjld52hkn05a9.apps.googleusercontent.com',
    iosBundleId: 'com.shark.notes',
  );
}
